#source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraPopupView', :exclusive => true do
  pod "HaidoraPopupView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HaidoraPopupView", :path => "../"

  
end
